[package]
name = "exa"
version = "0.1.0"
authors = ["Travis Thieman <travis.thieman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
name = "exa"
path = "src/lib.rs"

[dependencies]
nom = "6.1.2"
regex = "1.5.4"
simple-error = "0.2.3"
itertools = "0.10.1"
fastrand = "1.4.1"
libretro-backend = "0.2.1"

[profile.release]
lto = true

[profile.dev]
lto = true